apiVersion: v1
kind: Pod
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage-app
spec:
  containers:
  - name: homepage
    image: soberdev/homepage:latest
    ports:
      - containerPort: 8080
        name: web-homepage
  imagePullSecrets:
  - name: regcred
        
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
spec:
  selector:
    app.kubernetes.io/name: homepage-app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: web-homepage